# ./Dockerfile
FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update && apt-get install -y git docker.io && rm -rf /var/lib/apt/lists/*
# Preinstall plugins (optional but recommended)
#COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
#RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt
